### ISSUE TITLE
Import conflict

### ISSUE THREAD

**Issue by deprale** [driplet/backend#3]
Even when running a pyenv or a docker image, the following error ensues upon running app.py
Tried to fix it but I have no clue lol, tried using different versions and whatntot.
```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)

```

**Comment by deprale** [comment]
Fixed it.

To use it in a pyenv just modify the requirements.txt to use flask==2.0.3 instead and to fix the next issue which is gonna be 
```
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/path/venv/lib/python3.8/site-packages/flask/helpers.py)
```

just edit that file and change line 14 to import from flask.scaffold rather than flask.helpers, and you should be good to go.
